---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post-no-author
  - post
  - post-with-rating
  - post-no-featured-image
upload_dir: uploads
public_path: ''
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
